### ISSUE TITLE
Checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by jordynbx** [jordynbx/stardewValleyAssistant#2]
@pawaitemadisoncollege checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
What a fun project @jordynbx! As you mentioned, I think there's great benefit to writing a project in a couple different languages like this! Hopefully the fact that you worked on a php version means you've already made some of the key decisions and have some UI you can use. I'll be interested to hear how writing this in Java compares to PHP.

Your checkpoint prep looks very good. A few comments/questions:

 - [ ] it might be nice to provide a quick overview of Stardew Valley in your readme.md for those not already in the know. - [ ] I think if you add a space between the  `#`and `J` here:
![formatting](https://user-images.githubusercontent.com/13874466/107545405-dc467600-6b90-11eb-99b3-5da1bdfafa99.png)  the formatting will improve.  
- [ ] Because CRUD (create, read, update and delete) are required for the project, are there any update and delete user stories that you could add to the mvp?
- [ ] Some technologies are likely not needed here or should be updated for your project. 
![Screen Shot 2021-02-10 at 11 13 29 AM](https://user-images.githubusercontent.com/13874466/107545591-17e14000-6b91-11eb-9208-4de2d91f37e7.png)
- [ ] The screens had Recent search items and a Password reset? Are these represented in the user stories?
- [ ] Is "check which items I have already saved and check off new items" represented in the wireframes/screens? Maybe this happens on the search screens?
- [ ] Have you thought about an api or web service that might work well in your application?  I'm not sure if there are any Stardew Valley apis that might add value? Or perhaps email functionality using Javamail might be helpful => a way to notify an admin if there's an item missing, bad info, etc.

**Comment by jordynbx** [comment]
Thank you for all of the comments! To clarify, I didn't build this in PHP - it's totally new to me. I built a different project in PHP, an elaborate crop calculator, so unfortunately that doesn't give me any kind of head start. But I will probably use the same bootstrap theme to match the styling. 

For your first point, I agree and I will definitely add that. I think a brief overview of Stardew Valley will help people who haven't played the game what understand what it is and how my project benefits it. 

I think I can add the ability for users to add notes about each item to the project. That way they could update and delete their notes. I will add that into my user stories. 

Checking off items is in the wireframes - that is the little boxes next to items on the logged in screen and then viewing all of their items is on the My Items screen. Since that happens on two different screens, it sounds like I should make it two separate user items?

I really wanted to use an API and thought I would be able to because I thought I remembered there being one, but I can't find one anywhere that has the info I need so it looks like I'll need to input all the information manually which is going to be a headache. But adding something with Javamail could work. I will look into that. 

Sorry it took me so long to reply to this. Overall I have felt so behind and stressed. I feel concerned that I didn't pick a good project for this and and that it's too complex in the wrong ways. When mapping out my database I also was trying to think of all the database best practices I know in terms of splitting things off into different tables, but I'm worried that's going to make things needlessly complex and require me to have a lot more tables that require elaborate foreign key mapping to make everything work. I'm hoping that now that I understand what's going on a bit more things will move faster, but to be honest I've felt defeated lately and like this class is just too much work for me to get on top of.

I will update this issue again when I've resolved everything above, but I wanted to add least leave a comment now since it's taken me longer than I hoped to address it.

**Comment by jordynbx** [comment]
@pawaitemadisoncollege Thank you for the feedback! Here is what I have addressed so far:

- I updated the README to include a description of Stardew Valley
- I created a set of of CRUD MVPs around user notes functionality
- I removed the extra web service technologies from the README
- I added the password reset to User Stories
- I am reconsidering the recent search items - might push that to an "if i have time", and if so, will update my design documents and user stories accordingly 
- I added additional time to my project plan to research a web service this week. There is nothing directly related to Stardew Valley I've found so far, but Javamail is a good suggestion that I am going to look into.
