### ISSUE TITLE
Week 4 ready for review 

### ISSUE THREAD

**Issue by jordynbx** [jordynbx/stardewValleyAssistant#3]
@pawaitemadisoncollege week 4 is ready for review 

I found getting through the whole Hibernate demo challenging and a bit confusing, but then it was much easier once I implemented it on my project. I implemented it on my project in the easiest place for me to start, but near the end I realized that I was implementing it for admin functionality that wasn't even in my original project plan, and that I may not have time to create during this semester unless I change the scope/plan for my project. So I will likely need to go back and reimplement it on a different table I haven't created yet and remove it from the item table (unless I add in admin functionality this would work for), because I don't want general users to be adding/removing things from the main Item table. 

I think the most challenging thing for me right now is all the new language used with Hibernate. I'm using to just being able to write code and to know and understand exactly what I'm writing, and right now I feel a lot more lost. There is no way I could have completed this weeks assignment without referencing my completed demo the whole time, and it's hard to not always understand why exactly I'm writing what I'm writing because I don't have a handle on the new language yet. I didn't use any outside resources on this except for trying to troubleshoot intellij issues, like the one I posted about on slack with the coverage package being out of scope.

**Comment by pawaitemadisoncollege** [comment]
HI @jordynbx!  I understand how you are feeling - there is a LOT in the first weeks of this class, not just Hibernate but a whole bunch of other tech too! I hope having two weeks on Hibernate will help some of it stick; after that you'll get lots of practice as you add more tables/entities to your project. Writing the next entity in the one-to-many relationship might add a few new challenges, overall the entity and unit testing will be similar.  

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedItem.equals(actualItem));` so that you don't have to compare each instance var/column manually like this: https://github.com/jordynbx/stardewValleyAssistant/blob/fa6983e219f43b464c1971f0f8830c47859b911c/src/test/java/edu/matc/persistence/ItemDaoTest.java#L55
- [ ] Reminder to update your time log/journal and project plan (check off what's complete and add in the next several weeks).
